apiVersion: v1
kind: Secret
metadata:
  name: boleto-service-secrets
type: Opaque
stringData:
  datasource-url: jdbc:postgresql://postgres:5432/recebimentos
  datasource-username: recebimentos
  datasource-password: change-me
