apiVersion: v1
kind: Service
metadata:
  name: boleto-service
  labels:
    app: boleto-service
spec:
  selector:
    app: boleto-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
