apiVersion: v1
kind: Secret
metadata:
  name: recebimentos-secrets
  namespace: recebimentos
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: recebimentos
  SPRING_DATASOURCE_PASSWORD: change-me
  RDS_ENDPOINT: receber-bank-dev-postgres.xxxxxx.us-east-1.rds.amazonaws.com
  REDIS_ENDPOINT: receber-bank-dev-redis.xxxxxx.cache.amazonaws.com
  MSK_BOOTSTRAP_SERVERS: broker-1:9092,broker-2:9092
  BOLETO_GENERATION_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/000000000000/receber-bank-dev-boleto-generation
  AWS_S3_DOCUMENTS_BUCKET: receber-bank-dev-boleto-documents
  AWS_SNS_ALERTS_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:receber-bank-dev-alerts
