server:
  port: 8082

spring:
  application:
    name: query-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recebimentos_query}
    username: ${SPRING_DATASOURCE_USERNAME:recebimentos}
    password: ${SPRING_DATASOURCE_PASSWORD:recebimentos}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: query-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.bank.recebimentos.domain.event

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  kafka:
    topics:
      boleto-gerado: boleto.gerado
      pagamento-efetivado: pagamento.efetivado
      notificacao-enviada: notificacao.enviada
